{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "forge.fullname" . }}-agent
  labels:
    {{- include "forge.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "forge.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: agent
{{- end }}
