apiVersion: v1
kind: Namespace
metadata:
  name: opa
  labels:
    kubernetes.io/metadata.name: opa
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
